// Java class gobindings.Gobindings is a proxy for talking to a Go program.
//   gobind -lang=java github.com/conejoninja/gobindings
//
// File is generated by gobind. Do not edit.
package gobindings;

import go.Seq;

public abstract class Gobindings {
    static {
        Seq.touch(); // for loading the native library
        _init();
    }
    
    private Gobindings() {} // uninstantiable
    
    // touch is called from other bound packages to initialize this package
    public static void touch() {}
    
    private static native void _init();
    
    private static final class proxyMyInterface implements Seq.Proxy, MyInterface {
        private final Seq.Ref ref;
        
        @Override public final int incRefnum() {
              int refnum = ref.refnum;
              Seq.incGoRef(refnum);
              return refnum;
        }
        
        proxyMyInterface(Seq.Ref ref) { this.ref = ref; }
        
        public native void methodOne();
    }
    
    
    // skipped variable MyArray with unsupported type: *types.Array
    
    public static native void setMyBoolean(boolean v);
    public static native boolean getMyBoolean();
    
    public static native void setMyByte(byte v);
    public static native byte getMyByte();
    
    public static native void setMyByteSlice(byte[] v);
    public static native byte[] getMyByteSlice();
    
    public static native void setMyError(java.lang.Exception v);
    public static native java.lang.Exception getMyError();
    
    public static native void setMyFloat32(float v);
    public static native float getMyFloat32();
    
    public static native void setMyFloat64(double v);
    public static native double getMyFloat64();
    
    public static native void setMyInt(long v);
    public static native long getMyInt();
    
    public static native void setMyInteger16(short v);
    public static native short getMyInteger16();
    
    public static native void setMyInteger32(int v);
    public static native int getMyInteger32();
    
    public static native void setMyInteger64(long v);
    public static native long getMyInteger64();
    
    public static native void setMyInteger8(byte v);
    public static native byte getMyInteger8();
    
    // skipped variable MyMap with unsupported type: *types.Map
    
    // skipped variable MyPointer with unsupported type: *types.Pointer
    
    public static native void setMyRune(int v);
    public static native int getMyRune();
    
    // skipped variable MySlice with unsupported type: *types.Slice
    
    public static native void setMyString(String v);
    public static native String getMyString();
    
    public static native void normalFunc();
    public static native String normalFuncReturn();
    public static native String normalFuncReturnError() throws Exception;
    public static native void normalFuncWithParameters(String a, String b, String c, String d, long e, long f, long g, long h);
    // skipped function VariadicFuncInt with unsupported parameter or return types

}
