// Java class gobindings.MyInterface is a proxy for talking to a Go program.
//   gobind -lang=java github.com/conejoninja/gobindings
//
// File is generated by gobind. Do not edit.
package gobindings;

import go.Seq;

public interface MyInterface {
    public void methodOne();
    
}

