// Java class gobindings.MyStruct is a proxy for talking to a Go program.
//   gobind -lang=java github.com/conejoninja/gobindings
//
// File is generated by gobind. Do not edit.
package gobindings;

import go.Seq;

public final class MyStruct implements Seq.Proxy {
    static { Gobindings.touch(); }
    
    private final Seq.Ref ref;
    
    @Override public final int incRefnum() {
          int refnum = ref.refnum;
          Seq.incGoRef(refnum);
          return refnum;
    }
    
    MyStruct(Seq.Ref ref) { this.ref = ref; }
    
    public MyStruct() { this.ref = __New(); }
    
    private static native Seq.Ref __New();
    
    public final native long getMyInt();
    public final native void setMyInt(long v);
    
    public native void inc();
    @Override public boolean equals(Object o) {
        if (o == null || !(o instanceof MyStruct)) {
            return false;
        }
        MyStruct that = (MyStruct)o;
        long thisMyInt = getMyInt();
        long thatMyInt = that.getMyInt();
        if (thisMyInt != thatMyInt) {
            return false;
        }
        return true;
    }
    
    @Override public int hashCode() {
        return java.util.Arrays.hashCode(new Object[] {getMyInt()});
    }
    
    @Override public String toString() {
        StringBuilder b = new StringBuilder();
        b.append("MyStruct").append("{");
        b.append("MyInt:").append(getMyInt()).append(",");
        return b.append("}").toString();
    }
}

